/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.13
 * Generated at: 2022-02-22 16:02:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Arrays;
import java.util.List;
import java.sql.*;

public final class verCartas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"img/orco.ico\">\n");
      out.write("<meta charset=\"US-ASCII\">\n");
      out.write("<link rel=\"stylesheet\" href=\"Estilos/estilosCartaRandom.css\">\n");
      out.write("<title>Rpg Card Generator</title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<h1 class=\"titol\">Visualitzar cartes</h1>\n");
      out.write("<ul class=\"breadcrumb\">\n");
      out.write("	<a href='index.jsp'>\n");
      out.write("		<button class=\"button-29\" role=\"button\">Volver</button>\n");
      out.write("	</a>\n");
      out.write("\n");
      out.write("</ul>\n");
      out.write("<br>\n");
      out.write("<br>\n");

//  variables per fer la connexio:
String user = "m8";
String password = "yamuza";
String host = "localhost";
String db = "cartas_m8";
String url = "jdbc:mysql://" + host + "/" + db;
Connection conn = null;
Statement statement = null;
Statement num_registres = null;
ResultSet rs = null;
ResultSet num_reg = null;
int inicio;

//Limito la busqueda
int TAMANO_PAGINA = 2;

//examino la página a mostrar y el inicio del registro a mostrar
String pag = request.getParameter("pagina");
	int pagina=Integer.parseInt(pag);
	if (pagina==0) {
	   	inicio = 0;
	    pagina=1;
	}
	else {
	    inicio = (pagina - 1) * TAMANO_PAGINA;
	}
/**
//miro a ver el número total de campos que hay en la tabla con esa búsqueda
**/
Class.forName("com.mysql.jdbc.Driver").newInstance();
conn = DriverManager.getConnection(url, user, password);
num_registres = conn.createStatement();
//inmediatamente hacemos una consulta sencilla
//creamos la consulta
num_reg = num_registres.executeQuery("SELECT * FROM Cartas;");
int num_total_registros = 0;
while (num_reg.next()) {
	num_total_registros++;
}

//calculo el total de páginas
int total_paginas = (int) Math.ceil(((double) num_total_registros / TAMANO_PAGINA));

//pongo el número de registros total, el tamaño de página y la página que se muestra

out.print("<p class='resultado'>Nombre de registres trobats: " + num_total_registros + "</p><br>");
out.print("<p class='resultado'>Es mostren pàgines de " + TAMANO_PAGINA + " registres cadascuna</p><br>");
out.print("<p class='resultado'>Mostrant la pàgina " + pagina + " de " + total_paginas + "</p>");
out.print("<div id='paginacion'>");
//out.print("<a href=VisualitzarCartes.jsp?pagina=2>"+2+"</a> ");
if (total_paginas > 1) {
	for (int i = 1; i <= total_paginas; i++) {
		if (pagina == i)
	//si muestro el índice de la página actual, no coloco enlace
	out.print(pagina);
		else
	//si el índice no corresponde con la página mostrada actualmente, coloco el enlace para ir a esa página
	out.print(" <span><a href=verCartas.jsp?pagina=" + i + ">" + i + "</a> </span>");
	}
}
out.print("</div>");
out.print("<div id='container'>");

out.print("<div id='container-box'>");
try {

	Class.forName("com.mysql.jdbc.Driver").newInstance();
	conn = DriverManager.getConnection(url, user, password);
	statement = conn.createStatement();
	//inmediatamente hacemos una consulta sencilla
	//creamos la consulta
	String sentence = "SELECT * from Cartas limit " + inicio + "," + TAMANO_PAGINA;
	rs = statement.executeQuery(sentence);
	//leemos la consulta
	while (rs.next()) {
		//mostramos los resultados obtenidos
		//out.println(rs.getString("ID_carta"));
		//String nom=request.getParameter("nom");
		

      out.write("\n");
      out.write("<div class=\"contenedor-cartas\">\n");
      out.write("<article>\n");
      out.write("<h1>");
out.print(rs.getString("NOM_carta"));
      out.write("</h1>\n");
      out.write("	<h2>\n");
      out.write("		Raza: ");

	out.print(rs.getString("RACE_carta"));
	
      out.write("<br>\n");
      out.write("	</h2>\n");
      out.write("	<div class=\"img-article\">\n");
      out.write("		<img src=\"");
out.print(rs.getString("PIC_carta"));
      out.write("\" height=\"100\"\n");
      out.write("			width=\"80\">\n");
      out.write("	</div>\n");
      out.write("	<ul>\n");
      out.write("		<li>FUE:");

		out.print(rs.getString("FUE_carta"));
		
      out.write("\n");
      out.write("		</li>\n");
      out.write("		<li>DES:");

		out.print(rs.getString("DES_carta"));
		
      out.write("\n");
      out.write("		</li>\n");
      out.write("		<li>CON:");

		out.print(rs.getString("CON_carta"));
		
      out.write("\n");
      out.write("	</ul>\n");
      out.write("	<ul>\n");
      out.write("		</li>\n");
      out.write("		<li>INT:");

		out.print(rs.getString("INT_carta"));
		
      out.write("\n");
      out.write("		</li>\n");
      out.write("		<li>SAB:");

		out.print(rs.getString("SAB_carta"));
		
      out.write("\n");
      out.write("		</li>\n");
      out.write("		<li>CAR:");

		out.print(rs.getString("CAR_carta"));
		
      out.write("\n");
      out.write("		</li>\n");
      out.write("	</ul>\n");
      out.write("	<div class=\"putos-vida\">\n");
      out.write("	\n");
      out.write("PV:");

out.print(rs.getString("PV_carta"));

      out.write("<br>\n");
      out.write("<table width=\"");
out.print(rs.getString("PV_carta"));
      out.write("\" bgcolor=\"red\">\n");
      out.write("	<tr>\n");
      out.write("		<td></td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("PM:");

out.print(rs.getString("PM_carta"));

      out.write("<br>\n");
      out.write("<table width=\"");
out.print(rs.getString("PM_carta"));
      out.write("\" bgcolor=\"blue\">\n");
      out.write("	<tr>\n");
      out.write("		<td></td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("	</div>\n");
      out.write("</article>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

}
//cerramos la conexión
rs.close();
} catch (SQLException error) {
out.print("Error de Conexión : " + error.toString());
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
